include classpath("application.conf")

queues {
  ovo-jobs {
    defaultVisibilityTimeout = 120 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue {
      name = "ovo-jobs-dlq"
      maxReceiveCount = 8
    }
  }
  ovo-jobs-dlq {}
}
